### ISSUE TITLE
Pull Request's mentioned on the page not redirecting

### ISSUE THREAD

**Issue by Tanmay000009** [PunitLodha/punitlodha.github.io#1]
Pull requests mentioned under [gsoc_report.md](https://github.com/PunitLodha/punitlodha.github.io/blob/main/content/posts/gsoc_report.md) won't behave as expected, due to a minor bug in the links. Links, as mentioned in the report, are :
`[#1350](https://github.com/CCExtractor/ccextractor/pulls/1350)`
but should be
`[#1350](https://github.com/CCExtractor/ccextractor/pull/1350)`

**Comment by PunitLodha** [comment]
Thanks
